### ISSUE TITLE
GenePool - docs

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#107]
List<Gene> poolOfGene

GenePool inicjalizujemy int = liczba genów do wygenerowania (w konstruktorze)

zależność: Evaluator(targer), Mutator(mutationChance)
finalne podawane przez konstruktor

testujemy evaluate() mutate() wywołujące zależności

**Comment by KamilKamilS** [comment]
GenePool class is responsible for changing gene in given generation by evoking method in proper order. GenePool is also a container for a genes that is constant in each generation. Genes are storred in a List.

class GenePool
private final MutatorService mutatorService;
private final Evaluator evaluatorImpl;
private List<Gene> poolOfGene;
private int poolSize;

Methods:
void generateGenes()
void makeMutation()
void evaluatFitness()


przesyłam propozycje :)
