### ISSUE TITLE
GenePool - extract all logic

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#146]
I know we wanted to have working version of this class and then make a refactor, but it is hurting me bad, that this class is so overloaded.

I propose to extract all logic from this class to GenePoolService and use its methods to perform evolution or mutation.

It will break a lot of tests and make some of documentation out of date, but I think this is necessary.
GenePool is overcrowded now and still growing and it is getting harder to control what happens there.

**Comment by KamilKamilS** [comment]
Agree :D
