### ISSUE TITLE
Stage2 - Evaluator - docs

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#20]
G1 char[] ,50
G2 ,60
G3 ,09

Hello world
fjfowehfofw 1562
Hfsjfo hfhse 2213
 e           2156

Evaluator G -> G.fitness

Crossover G+G -> G

Mutation G -> G

GenePool G{200}
Evaluator.evaluate
Crossover.cross(G1,G2)
Mutation(=.mutate

Main
Evaluation = WorldEvalutaion("H");

GenePool(Evaluation, Crossover, Mutation, RandomProvider)

=========================================
Evaluator
float setFitness(Gene)

EvaluatorImpl(char target)
Gene -> value[0] == target (100)

value[0] - różnica
========
target

98/100
99/100

100/100

2/100

**Comment by PawelDabrowski83** [comment]
I am thinking about formula to estimate how good is current value to the target value. The best I have for now is:
target / (target + delta)
where delta is difference between target and current value: mod(target - value)

This function obviously does not work if target=0, because we cannot divide by zero.

**Comment by PawelDabrowski83** [comment]
My friend who is studing math suggested this formula:
1 / (1+(delta/100)) for delta <= 100
50 / delta for delta > 100

it is valid for target=0 and it should be precise enough to generate different fitness even for lower delta (difference between target and value)

**Comment by PawelDabrowski83** [comment]
And he suggested this as a single formula. I tried it with different values and I think it will be very fine for us:
1 / (1+log(1+delta))

**Comment by KamilKamilS** [comment]
I have also fought about the formula and have a slightly different idea. 
My formula = (100 - delta) / 100  
where "100" is constant value.
delta - the difference between target and current char (the same as above)
instead of using the target value we can use simply 100. There is no problem with dividing by zero.
And the best fitness value is equal to 1. (100/100) where delta = 0.

What do you think about this?

**Comment by PawelDabrowski83** [comment]
Yes, but if I understand correctly the constant should be equal to max value of our target, because we want formula to work for maximum delta (max char value - min max value). Char in utf-8 takes values 0-65535, so 65535 is maximum delta.

This is the case, where our target is 'c', so number 99 and Genes takes some values - comparison of fitness from two formulas: https://ibb.co/xDXgSHF

If const value is smaller than max delta, we risk overflow: https://ibb.co/KjSn77z

But after all, we can implement both of this formulas or even more, because Evaluator is only an Interface and can have multiple variances of implementation.

**Comment by KamilKamilS** [comment]
I don't understand what do you mean by overflow.
I think that both formula works (when we use as a constant 65535 instead of 100)

I agree that we can implement both formulas or one and then considered if any changes in case of this formula are needed.

**Comment by PawelDabrowski83** [comment]
I will make tests for both of them :)
