### ISSUE TITLE
Stage3 - Gene has only one char - test

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#32]

**Comment by Surfboy678** [comment]
The documentation may void but in the code I have float.
Need to change in the documentation.
Everything works, anyway.

**Comment by PawelDabrowski83** [comment]
This is an issue for Gene and making sure that test are checking if Gene has a single char value field instead of char array

**Comment by Surfboy678** [comment]
When it comes to this setFitnes, if we put a single value in the array, it works, but if we want to use only the char variable, we would have to change the implementation of the class, but we probably stay with the array, because it's more universal?

**Comment by PawelDabrowski83** [comment]
We decided to stay with single char instead of char array. In next few steps we will use only single char Gene.

In future - maybe we will change it to Interface and prepare multiple implementations - one with single char, another with char[]. But for now it is unnecessary.
