### ISSUE TITLE
Gene.generateValue() hidden declaration

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#47]
I am not happy with having void method generateValue() in constructor, which indirectly sets this.value during object creation.

I think it should be
this.value = generateValue();
so method should return float value.

But I think it is a low priority change and we should consider this case in refactor later, and go to next steps of application first.

**Comment by KamilKamilS** [comment]
I agree we can change the method. Maybe next stage will additionally include this refactor.
