### ISSUE TITLE
Update docs for Evaluator

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#50]
It seems like a part of internal implementation and serves only one purpose - to save calculated value into Gene.value field.

I wonder if there is another context, where Evaluator.calculateFitness is used independently.

- [x] Update Evaluator description
- [x] Update class names
- [x] Update diagram
- [x] Update style for consistency (blockquote)

**Comment by PawelDabrowski83** [comment]
One case where we can use calculateFitness is if we want to check Gene fitness without modyfing state of the object. For example we have multiple variants of Evaluator interface and want to compare fitness values calculated by them. 

But I would argue that it is only a theoretical exercise, because value spread between 0-1 in each Evaluator impl. can be different and sometimes result 0.85 may indicate close match, and on another implementation the same result can indicate very weak match.

**Comment by KamilKamilS** [comment]
I have created docs in this way that Evaluator has a private method calculateFitness() only to calculate fitness and return a float. and setFitness() which is a public method and uses calculated fitness from the previous method and set I to a given gene. So I want just to split setFitness() method into two methods first calculate and then setFitness() method.

**Comment by KamilKamilS** [comment]
But maybe it is not needed because the method setFitness() that you have created is not so complex and maybe it can stay as it is now implemented

**Comment by PawelDabrowski83** [comment]
I was looking at our current diagram, which states that both methods are public, marked with plus sign.

**Comment by KamilKamilS** [comment]
Ok right my bad. Docs have no info about private method

**Comment by PawelDabrowski83** [comment]
Before advancing this issue, we might resolve #70

**Comment by KamilKamilS** [comment]
Additionally, I noticed that currently docs don't have a diagram with the evaluator. So updated diagram need to be added.

**Comment by PawelDabrowski83** [comment]
- [ ] Update Evaluator description
- [ ] Update class names
- [ ] Update diagram
- [ ] Update style for consistency (blockquote)

**Comment by PawelDabrowski83** [comment]
Added checkboxes in first message of this topic.
