### ISSUE TITLE
Stage 4 - CrossoverService - docs

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#52]
CrossoverService:
+cross(Gene gene1, Gene gene2): void

cross is mutating/mixing genes 1 and 2, using described pattern

MixingHalvesCrossoverServiceImpl:
g1: 1st byte of g1 + 2nd byte of g2
g2: 1st byte of g2 + 2nd byte of g1

OddBitesCrossoverServiceImpl:
g1: has bites with odd positions copied from g2
g2: has bites with odd positions copied from g1

EvenBitesCrossoverServiceImpl:
g1: has bites with even positions copied from g2
g2: has bites with even positions copied from g1

BitPairCrossoverServiceImpl:
g1: starting from bit0, two bits unmodified, then another two bits copied from g2, then two unmodified, and another from g2...

**Comment by KamilKamilS** [comment]
Very nice for me. We can start with these patterns.
