### ISSUE TITLE
Refactor names for Variant1 and Variant2 Evaluators

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#70]
My propositions are:

variant 1: 1 / (1+log10(1+delta))
LogarithmicEvaluatorImpl

variant 2: (65535 - delta) / 65535
MaxDeltaEvaluatorImpl

**Comment by PawelDabrowski83** [comment]
Please let me know what do you think @KamilKamilS

**Comment by KamilKamilS** [comment]
I agree with your proposal LogarithmicEvaluatorImpl and MaxDeltaEvaluatorImpl. These names will be much better than the previous one :)
