### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#75]
Adding license could encourage contributors to join in. Besides, I think it is a pro move and I have not done this before, but I want to try. :)

More info: https://choosealicense.com/

**Comment by PawelDabrowski83** [comment]
https://choosealicense.com/licenses/mit/ MIT licence is really short and should be enough. What do you think @KamilKamilS ?

**Comment by KamilKamilS** [comment]
Yes, for me this license is also fine. Is plain and simple and will be enough.
