### ISSUE TITLE
BitwiseUtils method should have throws keyword in declaration

### ISSUE THREAD

**Issue by KamilKamilS** [PawelDabrowski83/genAlgo#80]
In BitwiseUtil there are two methods setBit() and setByte(), which throw exceptions. Do you agree that these methods should also declare these exceptions?

**Comment by PawelDabrowski83** [comment]
You are right. I think we should use descriptive custom Exceptions extending IllegalArgumentException.

**Comment by PawelDabrowski83** [comment]
I realised my answer was for another question... Let us handle this step by step.
