### ISSUE TITLE
RandomProvider needs method to produce float values

### ISSUE THREAD

**Issue by PawelDabrowski83** [PawelDabrowski83/genAlgo#83]
We could continue with getRandom producing nextInt(), and then convert it to float values, but I think it is better to add getRandomFloat or just getFloat() method to RandomProvider.

**Comment by KamilKamilS** [comment]
Yes you have right, better will be to add new method :)

**Comment by PawelDabrowski83** [comment]
I am opening new issue to catch up with RandomProvider docs.
